name: Tutorial

on: push

jobs:
  Ejercicio:
    name: Ej code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      
      - name: Install dependencies
        run: python -n pip install --upgrade pip setuptools wheel
        
      - name: Test with pytest
        run:
          pip install pytest
          pytest
